version: '3.8'

services:
  backend1:
    build: .
    environment:
      - MONGO_URL= mongodb+srv://zedek:olaitan23CG@hotelroom.yo5eha6.mongodb.net/?retryWrites=true&w=majority&appName=hotelroom
    depends_on:
      - mongo

  backend2:
    build: .
    environment:
      - MONGO_URL= mongodb+srv://zedek:olaitan23CG@hotelroom.yo5eha6.mongodb.net/?retryWrites=true&w=majority&appName=hotelroom
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongodata:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2

volumes:
  mongodata:
